AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  line-reminder-bot

  Sample SAM Template for line-reminder-bot
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  LineChannelAccessToken:
    Type: String
  QstashToken:
    Type: String
  PaymentUri:
    Type: String

Resources:
  DynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: line-reminders
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: gsi1pk
          AttributeType: S
        - AttributeName: gsi1sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: gsi1pk-gsi1sk-index
          KeySchema:
            - AttributeName: gsi1pk
              KeyType: HASH
            - AttributeName: gsi1sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
  LineBotFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Connectors:
      DynamoTableConn:
        Properties:
          Destination:
            Id: DynamoTable
          Permissions:
            - Write
            - Read
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Timeout: 30
      MemorySize: 1024
      Architectures:
        - x86_64
      FunctionUrlConfig:
        AuthType: NONE
      Environment:
        Variables:
          LINE_CHANNEL_ACCESS_TOKEN: !Ref LineChannelAccessToken
          QSTASH_TOKEN: !Ref QstashToken
          PAYMENT_URI: !Ref PaymentUri
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - app.ts

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  LineBotFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt LineBotFunction.Arn
  LineBotFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt LineBotFunctionRole.Arn
